### ISSUE TITLE
Add tests workflow

### ISSUE THREAD

**Issue by yarikoptic** [dandi/redirector#17]
Inspired by #16

**Comment by jwodder** [comment]
@yarikoptic @satra One of the redirection routes in `serve.py` is for visiting a specific version of a Dandiset.  How can I find an example Dandiset on https://gui.dandiarchive.org that has versions?  Does a change in a Dandiset's version cause the Dandiset's Girder ID to change?  (EDIT: Actually, the route doesn't even use the "version" parameter.  Is that supposed to be like that?)

Also, would it be better for the test workflow to run the script via Docker in order to test that at the same time (and also make the script demonization simpler), or should that be left for a separate workflow?
