### ISSUE TITLE
make dandi-cli tests use the PR version of the redirector

### ISSUE THREAD

**Issue by yarikoptic** [dandi/redirector#42]
as green #40 and red #41 shows - ATM we test against deployed redirector.

**Comment by yarikoptic** [comment]
interestingly - it failed only for python 3.6... confused on why is that so -- is parsed by json record uses `defaultdict` in >= 3.7?

**Comment by jwodder** [comment]
@yarikoptic The integration tests install dandi-cli from PyPI rather than from the GitHub repository.  As we dropped Python 3.6 support a while ago, `pip install dandi` in Python 3.6 now installs an old version, the latest version of dandi that supported 3.6.  The particular test that's failing [was removed in January](https://github.com/dandi/dandi-cli/commit/f9fa14bd9ed464d982864eefd34349b3f043e979).

Regardless, the PR version of the redirector is already used for the Docker Compose setup; I'm not sure how to use it for whatever tests are currently hitting the production redirector.

**Comment by yarikoptic** [comment]
>  I'm not sure how to use it for whatever tests are currently hitting the production redirector.

if it is running on port 80 inside the container (or we map it) could we just overload dandiarchive.org in /etc/hosts so any test (of a released or not) dandi-cli would talk to the redirector from the PR, not the deployed one?  An alternative, if that doesn't work, could be to add support for overloading the URL for redirector via environment variable to dandi-cli (and then could probably even carry an alternative port number).

**Comment by jwodder** [comment]
@yarikoptic It appears that none of the tests in dandi-cli actually use the Dockerized redirector, and the only one that accesses the production redirector is [`test_utils:test_server_info`](https://github.com/dandi/dandi-cli/blob/e564fdb3a964f5170f67e48b0ff9034794f4ca0d/dandi/tests/test_utils.py#L366).  Also, the Dockerized redirector currently fails to start up due to a missing module error that is likely caused by a dependency mismatch.

**Comment by yarikoptic** [comment]
Could you please look into fixing up the dockerized redirector?

**Comment by jwodder** [comment]
@yarikoptic Docker image fixed: https://github.com/dandi/redirector/pull/45

**Comment by yarikoptic** [comment]
> the only one that accesses the production redirector is test_utils:test_server_info.

so I guess we need to make it test against dockerized one.  I guess you have attempted that in https://github.com/dandi/dandi-cli/pull/581 and the only issue is to figure out some ports mapping as you noted in https://github.com/dandi/dandi-cli/pull/581#issuecomment-822667819 . Or there is more to it?

**Comment by jwodder** [comment]
@yarikoptic It seems silly to integrate the two code bases just for a single test, especially when the test in question could easily be added to `test_serve.py` instead.

**Comment by yarikoptic** [comment]
It does feel a bit silly indeed but:
- I am not entirely sure why `dandi-cli` tests do not "run into redirector" in more code paths and situation might change in the future.  
- Adding to `test_serve.py` here, even with a big loud comment to not change it unless somehow (how?) tested against assumptions in `dandi-cli` would be inefficient and would not really provide any "integration testing".
